from time import sleep
liste1 =       [5, 6, 1, 8, 8, 9, 72, 47, 184, 79]
a_addieren = (5 + 6 + 1 + 8 + 8 + 9 + 72 + 47 + 184 + 79)
a = a_addieren / 10
print('Die erste liste: ', liste1)
sleep(1)
print('Die größte Zahl der ersten liste ist', max(liste1))
sleep(1)
print('Die kleinste Zahl der ersten liste ist', min(liste1))
sleep(1)
print('Der Mittelwert der ersten liste ist', a)
sleep(1)
print('                                    ')
liste2 = [44, 547, 1275, 528, 1548, 4600, 12, 88]
b_addieren = (44 + 547 + 1275 + 528 + 1548 + 4600 + 12 + 88)
b = b_addieren / 8
sleep(1)
print('Die zweite liste: ', liste2)
sleep(1)
print('Die größte Zahl der zweiten liste ist', max(liste2))
sleep(1)
print('Die kleinste Zahl der zweiten liste ist', min(liste2))
sleep(1)
print('Der Mittelwert der zweiten liste ist', b)
sleep(1)
print('                           ')
liste3 = ['Hallo', ' Hi', "wie geht's", 'Name', 'Nachname']
c = max(liste3, key = len)
sleep(1)
print('Die dritte liste:',liste3)
sleep(1)
print('Das längste Wort in der dritten liste ist', c)
sleep(1)
print('                         ')
liste4 = ['Moamen', 'sharmarke', 'Mateja', 'Jonas']
d = max(liste4, key = len)
sleep(1)
print('Die vierte liste: ', liste4)
sleep(1)
print('Das längste Wort in der vierten liste ist', d)
sleep(1)
print('                                  ')
liste5 = ['Hund', 'Schwein', 'Katze']
e = max(liste5, key = len)
sleep(1)
print('Die fünfte liste: ', liste5)
sleep(1)
print('Das längste Wort in der fünften liste ist', e)
sleep(1)
print('                                   ')
liste6 = ['obst', 'Kartoffeln', 'Pizza']
f = max(liste6, key = len)
sleep(1)
print('Die sechste liste: ', liste6)
sleep(1)
print('Das längste Wort in der sechsten liste ist', f)
sleep(1)