z1 = float(input('Gib eine zahl ein:'))
z2 = float(input('Gib eine zahl ein:'))
z3 = float(input('Gib eine zahl ein:'))
z4 = float(input('Gib eine zahl ein:'))
z5 = float(input('Gib eine zahl ein:'))
z6 = float(input('Gib eine zahl ein:'))
z7 = float(input('Gib eine zahl ein:'))
z8 = float(input('Gib eine zahl ein:'))
z9 = float(input('Gib eine zahl ein:'))
z10 = float(input('Gib eine zahl ein:'))

Liste =[]
Liste.append(z10)
Liste.append(z1)
Liste.append(z2)
Liste.append(z3)
Liste.append(z4)
Liste.append(z5)
Liste.append(z6)
Liste.append(z7)
Liste.append(z8)
Liste.append(z9)
print(Liste)